name: manda2
description: A new Flutter application.

version: 21.0.0+121

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_alert: ^0.4.0
  flutter_credit_card: ^0.1.3
  shimmer: ^1.0.1
  cupertino_icons: ^0.1.2
  google_fonts: ^1.0.0
  flutter_datetime_picker: ^1.4.0
  jiffy: ^3.0.1
  flutter_cupertino_localizations: ^1.0.1
  shared_preferences: ^0.5.7
  sliding_up_panel: ^0.3.6
  mask_text_input_formatter: ^1.0.5
  flutter_masked_text: ^0.8.0
  rflutter_alert: ^1.1.0
  network_to_file_image: ^2.2.4
  image_picker: ^0.6.1
  url_launcher: ^5.2.5
  flutter_socket_io: ^0.6.0
  flutter_cupertino_data_picker: ^0.8.6
  provider: ^4.0.2
  numeral: ^1.0.4
  rate_my_app: ^0.6.1+3
  pull_to_refresh: ^1.5.8
  date_format: ^1.0.8
  flutter_mailer: ^0.4.1+2
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  firebase_core: ^0.4.5
  firebase_storage: ^3.1.6
  emoji_picker: ^0.1.0
  dotted_border: ^1.0.6
  firebase_messaging: ^6.0.16
  firebase_admin: ^0.1.3
  charts_flutter: ^0.9.0
  percent_indicator: ^2.1.7+4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - storage/